# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from wallflower_sidecar import wallflower_analysis_pb2 as wallflower__analysis__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in wallflower_analysis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalysisServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeJam = channel.unary_stream(
                '/wallflower.analysis.AnalysisService/AnalyzeJam',
                request_serializer=wallflower__analysis__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=wallflower__analysis__pb2.AnalysisProgress.FromString,
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/wallflower.analysis.AnalysisService/GetHealth',
                request_serializer=wallflower__analysis__pb2.HealthRequest.SerializeToString,
                response_deserializer=wallflower__analysis__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetHardwareInfo = channel.unary_unary(
                '/wallflower.analysis.AnalysisService/GetHardwareInfo',
                request_serializer=wallflower__analysis__pb2.HardwareInfoRequest.SerializeToString,
                response_deserializer=wallflower__analysis__pb2.HardwareInfoResponse.FromString,
                _registered_method=True)


class AnalysisServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeJam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHardwareInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeJam': grpc.unary_stream_rpc_method_handler(
                    servicer.AnalyzeJam,
                    request_deserializer=wallflower__analysis__pb2.AnalyzeRequest.FromString,
                    response_serializer=wallflower__analysis__pb2.AnalysisProgress.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=wallflower__analysis__pb2.HealthRequest.FromString,
                    response_serializer=wallflower__analysis__pb2.HealthResponse.SerializeToString,
            ),
            'GetHardwareInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHardwareInfo,
                    request_deserializer=wallflower__analysis__pb2.HardwareInfoRequest.FromString,
                    response_serializer=wallflower__analysis__pb2.HardwareInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wallflower.analysis.AnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wallflower.analysis.AnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalysisService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeJam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/wallflower.analysis.AnalysisService/AnalyzeJam',
            wallflower__analysis__pb2.AnalyzeRequest.SerializeToString,
            wallflower__analysis__pb2.AnalysisProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallflower.analysis.AnalysisService/GetHealth',
            wallflower__analysis__pb2.HealthRequest.SerializeToString,
            wallflower__analysis__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHardwareInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallflower.analysis.AnalysisService/GetHardwareInfo',
            wallflower__analysis__pb2.HardwareInfoRequest.SerializeToString,
            wallflower__analysis__pb2.HardwareInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
